name: 'Build Documentation & QA'
on:
  workflow_run:
    workflows: ["master_build"]
    branches: [ master ]
    types:
      - completed

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build Microservice Docs
    services:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install graphviz gsfonts graphviz-doc
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Server"
      - name: Site
        run: >
          ./mvnw post-integration-test site scm-publish:publish-scm
          -DM2_REPO_DIR=/home/runner/.m2/repository
          -DsurefireArgs=-Dspring.profiles.active=TEST
          -Dargs=-Dspring.profiles.active=TEST
          -Dscmuser=$PUSHKEY
          -Dscmpublish.pubScmUrl=scm:git:https://openwms:$PUSHKEY@github.com/openwms/org.openwms.wms.movements.git
          -DdeveloperConnectionUrl=scm:git:https://openwms:$PUSHKEY@github.com/openwms/org.openwms.wms.movements.git
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -Prelease -B $MAVEN_OPTS
        env:
          PUSHKEY: ${{ secrets.PUSHKEY }}
